apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: job-ns
  name: patch-pods-role
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "services", "pods", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-pods-binding
  namespace: job-ns
subjects:
- kind: ServiceAccount
  name: default
  namespace: job-ns
roleRef:
  kind: Role
  name: patch-pods-role
  apiGroup: rbac.authorization.k8s.io